=== GiN2K/Sokoban-MonoGame/Sokoban/Content/File.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.amodifer.com/XnaContent"
           xmlns="http://www.amodifer.com/XnaContent"
           xmlns:ns="Microsoft.Xna.Framework"
           elementFormDefault="qualified">

    <!-- ici Declaration d'un élément racine de nom XnaContent et de type XnaContentType -->
    <xs:element name="XnaContent" type="XnaContentType"/>

    <!-- Definition du type Complexe XnaContentType de l'élément racine XnaContent -->
    <xs:complexType name="XnaContentType">
        <xs:sequence>
            <xs:element name="Asset" type="AssetType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition du type Complexe Definition du type Complexe de l'élément Asset  -->
    <xs:complexType name="AssetType">
        <xs:sequence>
            <xs:element name="Item" type="LevelType" maxOccurs="unbounded"/>
        </xs:sequence>
         <xs:attribute name="Type" type="AssetTypeAttributeType" use="required"/>  
    </xs:complexType>

    <!-- Definition du type Simple AssetTypeAttributeType  -->
     <xs:simpleType name="AssetTypeAttributeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="System.Collections.Generic.List[System.Collections.Generic.List[string]]"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Definition de type Complexe pour Level (Item) -->
    <xs:complexType name="LevelType">
       <xs:sequence>
           <xs:element name="Item" type="RowType" minOccurs="10" maxOccurs="10"/>
       </xs:sequence>
    </xs:complexType>


    <!-- Definition du type Simple pour Row (Item) avec pattern -->
    <xs:simpleType name="RowType">
        <xs:restriction base="xs:string">
            <!-- 
                Cette expression régulière valide la ligne composée de 20 éléments séparés par des virgules
                Chaque élément peut être :
                - #
                - Un espace ( )
                - P
                - B
                - .
                      -->
           <xs:pattern value="^([#PB\.p ]\,){19}[#PB\.p ]$"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== GiN2K/Sokoban-MonoGame/Sokoban/Content/File.xml
<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:ns="Microsoft.Xna.Framework"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.amodifier.com/XnaContent"
            xsi:schemaLocation="http://www.amodifier.com/XnaContent Content/File.xsd">
    <Asset Type="System.Collections.Generic.List[System.Collections.Generic.List[string]]">
        <!--Level 1 -->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,P, , , , , ,#,#,#, , ,.,., , ,#,#,#</Item>
            <Item>#,#,#,#, ,#, ,#,#, ,#, ,B, , ,#, ,#,#,#</Item>
            <Item>#,#, ,#, ,#, , , , , ,#, ,#, ,#, ,#,#,#</Item>
            <Item>#,#, , , , , ,#,#,#, , , ,#,B, , , ,#,#</Item>
            <Item>#,#,#,#,#,#,#, , , , , , ,#, , , ,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
         <!-- Level 2 -->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> , , ,#,#,#,#,#,#,#, , ,#,#,#,#,#,#,#,#</Item>
            <Item> , ,#,#, , ,#, , ,#,#, ,#,#,#,#,#,#,#,#</Item>
            <Item> ,#,#,.,.,., ,.,.,.,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#, ,B,#,B,#,B,B,B, ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,P, , ,#, , , , ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#, , ,#,#,#, ,#, ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , ,#, ,#, , , ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
      <!--Level 3-->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#, , , ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,.,P,B, , ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#, ,B,.,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,.,#,#,B, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#, ,#, ,., ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,B, ,.B,B,B,.,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#, , , ,., , ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
        <!--Level 4-->
        <Item>
            <Item>#,#,#,#,#,#,#,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , , , ,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#,#,#,#, ,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#, , ,#, ,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#, , ,#, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,.,.,.,.,., ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#, ,B,B,B,B,B, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#,#,#,P,#, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> , , ,#, , , ,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> , , ,#,#,#,#,#, , ,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
        <!-- Level 5 -->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#, , ,#,#,#,#,#,#</Item>
            <Item>#,.,., , ,#, , , , , ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,., , ,#, ,B, , ,B, , ,#,#,#,#,#,#,#</Item>
            <Item>#,.,., , ,#,B,#,#,#,#, , ,#,#,#,#,#,#,#</Item>
            <Item>#,.,., , , , ,P, ,#,#, , ,#,#,#,#,#,#,#</Item>
            <Item>#,.,., , ,#, ,#, , ,B, ,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#, ,#,#,B, , , ,#,#,#,#,#,#,#</Item>
            <Item> , ,#, ,B, , ,B, ,B, , , ,#,#,#,#,#,#,#</Item>
            <Item> , ,#, , , , ,#, , , , , ,#,#,#,#,#,#,#</Item>
            <Item> , ,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
        <!-- Level 6 -->
        <Item>
            <Item> , , , , , , , ,#,#,#,#,#,#,#,#, ,#,#,#</Item>
            <Item> , , , , , , , ,#, , , , , ,P,#, ,#,#,#</Item>
            <Item> , , , , , , , ,#, ,B,#,B, ,#,#, ,#,#,#</Item>
            <Item> , , , , , , , ,#, ,B, , ,B,#, , ,#,#,#</Item>
            <Item> , , , , , , , ,#,#,B, ,B, ,#, , ,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#, ,B, ,#, ,#,#,#,#,#,#</Item>
            <Item>#,.,.,., , ,#,#,#, ,B, , ,B, , ,#,#,#,#</Item>
            <Item>#,#,.,., , , , , ,B, , ,B, , , ,#,#,#,#</Item>
            <Item>#,.,.,., , ,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#, , , , , , , , , ,#,#,#</Item>
        </Item>
        <!-- Level 7 -->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#, , , , , , , , , , ,#</Item>
            <Item>#,#,#,#,#, , , ,#, , , , , , , , , , ,#</Item>
            <Item>#,#,#,#,#,B, , ,#, , , , , , , , , , ,#</Item>
            <Item>#,#,#,#,#, , ,B,#,#, , , , , , , , , ,#</Item>
            <Item>#,#,#, , ,B, ,B, ,#, , , , , , , , , ,#</Item>
            <Item>#,#,#, ,#, ,#,#, ,#, , , ,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#, ,#,#, ,#,#,#,#,#, , ,.,.,#,#</Item>
            <Item>#, ,B, , ,B, , , , , , , , , , ,.,.,#,#</Item>
            <Item>#,#,#,#,#, ,#,#,#, ,#,P,#,#, , ,.,.,#,#</Item>
            <Item>#,#,#,#,#, , , , , ,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
        <!-- Level 8 -->
        <Item>
            <Item>#,#,#,#, , , , , , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,., , , , , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,#,B,B,B,B,B,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#,#,.,.,.,.,.,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,#, , ,B, , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#, ,#,#,#,#, ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , , , , , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#,#, , ,P,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
      <!-- Level 9 -->
        <Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> , , ,#,#,#,#,#, , , ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#, , , ,#, , , ,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,#,B, , ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,B,B, , , , , , ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,P, , ,#,B, ,B,#, ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#, ,#, , , ,#, ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#, , ,#,#,#,#,#, ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#, , ,.,.,.,.,., ,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>

        <!-- Level 10 -->
        <Item>
            <Item>#,#,#,#,#, ,#,#,#,#, , , ,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#,#,#, , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,.,.,.,.,.,.,., , ,#,#,#,#,#,#,#,#</Item>
            <Item> ,#, ,#,#,B,#, , ,#, , ,#,#,#,#,#,#,#,#</Item>
            <Item> ,#, , , ,B,P,#, ,#, ,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#,#,B,B,B,B,B, ,#, ,#, ,#,#,#,#,#,#,#</Item>
            <Item> , ,#, ,#, , ,#,#,#, ,#, ,#,#,#,#,#,#,#</Item>
            <Item> , ,#, , , , , , , , ,#, ,#,#,#,#,#,#,#</Item>
            <Item> , ,#,#,#,#,#,#,#, , ,#, ,#,#,#,#,#,#,#</Item>
            <Item> , , , , , , , ,#,#,#,#, ,#,#,#,#,#,#,#</Item>
        </Item>
        <!-- Level 11 -->
        <Item>
            <Item>#,#,#,#,#,#,#, , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , , ,#, , ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,#,#,#, ,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,#, ,B, ,B, ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,#, , ,P, , ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,#, ,B, ,B, ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,#,#,#,P, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , , , ,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , ,#,#,#,#,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#, , , , , , ,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>
        <!-- Level 12 -->
        <Item>
            <Item> ,#,#,#,#,#,#,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item> ,#,P, , , , ,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,B,#,#,B,B,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,B, , , , ,#, ,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, ,#,#,B,#, ,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,.,.,.,.,.,.,.,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#, ,#,#, , ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , , , ,B,B,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#, , , ,#, , , ,#,#,#,#,#,#,#,#,#,#,#,#</Item>
            <Item>#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#,#</Item>
        </Item>

    </Asset>
</XnaContent>
